language: rust
rust:
  - stable
  - beta
  - nightly
  - 1.34.0
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
  include:
    - rust: stable
      script: 'cargo bench'
cache: cargo
